name: Say Hello

on:
  push:
    branches:
      - develop

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hola mundo!"
